version: '3.8'
services:
  sentinel:
    build: .
    ports:
      - '5000:5000'
    environment:
      - CPU_ALERT_THRESHOLD=85
      - MEM_ALERT_THRESHOLD=90
      # Add SLACK_WEBHOOK, SMTP_* and AWS_* via env or docker secrets