name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install deps & test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q

  docker-scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker build -t cloudops-sentinel:ci .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: cloudops-sentinel:ci
          severity: HIGH,CRITICAL
          exit-code: '1'